### 원본 : https://github.com/rougier/numpy-100
### 한국어 Python 2.7 버전 譯 : https://github.com/dandelin/numpy-100

1\. numpy import하기

In [1]:
import numpy as np

2\. numpy 버전과 설정 출력하기

In [2]:
print np.__version__
np.__config__.show()

1.10.1
lapack_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd', 'mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd']
    library_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/include']
blas_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd']
    library_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp6

3\. 크기 10인 영벡터 어레이 만들기

In [3]:
Z = np.zeros(10)
print Z

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


4\. 커맨드라인에서 numpy add 함수의 documentation 가져오기

In [4]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


5\. 크기가 10인 벡터 어레이인데, 다섯번째 인덱스의 값은 1이고 나머지는 0인 벡터 만들기

In [5]:
Z = np.zeros(10)
Z[4] = 1
print Z

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


6\. 10으로 시작해서 49로 끝나는 정수 벡터 어레이 만들기

In [6]:
Z = np.arange(10, 50)
print Z

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7\. 벡터 어레이 거꾸로 뒤집기

In [7]:
Z = np.arange(50)
Z = Z[::-1]
print Z

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


8\. 0으로 시작해서 8로 끝나는 3 x 3 정수 행렬 어레이 만들기

In [8]:
Z = np.arange(9).reshape(3, 3)
print Z

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9\. 벡터 어레이 [1, 2, 0, 0, 4, 0]에서 0이 아닌 수의 인덱스를 구하기

In [9]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print nz

(array([0, 1, 4], dtype=int64),)


10\. 3 x 3 단위행렬 어레이 구하기

In [10]:
Z = np.eye(3)
print Z

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


11\. 랜덤한 값이 들어간 3 x 3 x 3 3차원 행렬 어레이 구하기

In [11]:
Z = np.random.random((3, 3, 3))
print Z

[[[ 0.31328919  0.00739354  0.15699596]
  [ 0.80873822  0.22534433  0.64647591]
  [ 0.58698509  0.85300308  0.90262955]]

 [[ 0.1836905   0.63815721  0.8447391 ]
  [ 0.43816622  0.08291757  0.56451726]
  [ 0.82415176  0.10811578  0.90943572]]

 [[ 0.71531527  0.00980151  0.35115836]
  [ 0.23922001  0.82754994  0.22380765]
  [ 0.18341876  0.45837718  0.2250295 ]]]


12\. 랜덤한 값이 들어간 10 x 10 행렬 어레이를 만들고 그 어레이에서 최솟값과 최댓값 구하기

In [12]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print Zmin, Zmax

0.0269383199096 0.95393461328


13\. 랜덤한 값이 들어간 크기가 30인 벡터 어레이를 만들고 평균값 구하기

In [13]:
Z = np.random.random(30)
m = Z.mean()
print m

0.430380602607


14\. 대각선 아래 값들이 각각 1, 2, 3, 4인 5 x 5 행렬 어레이 만들기

In [14]:
Z = np.diag(1 + np.arange(4), k = -1)
print Z

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


15\. 바둑판 패턴의 8 x 8 행렬 어레이 만들기

In [15]:
Z = np.zeros((8, 8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print Z

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


16\. 바둑판 패턴의 8 x 8 행렬 어레이를 tile 함수를 사용하여 만들기

In [16]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print Z

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


17\. 5 x 5 랜덤 행렬 어레이를 min-max normalize 하기 

In [17]:
Z = np.random.random((5, 5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print Z

[[ 0.71829961  0.24474107  0.6901774   0.41628253  0.36887547]
 [ 0.85626086  0.34401069  0.34486816  0.7175817   0.14211143]
 [ 0.75384664  0.61378919  0.09100907  0.11322678  0.98439684]
 [ 0.9730586   0.6555595   0.0741328   0.74081398  0.94371656]
 [ 0.          0.01104585  1.          0.93410349  0.315242  ]]


18\. 5 x 3 행렬 어레이와 3 x 2 행렬 어레이 곱하기

In [18]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print Z

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


19\. 행의 값이 0부터 4까지의 정수값인 5 x 5 행렬 어레이 만들기

In [19]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print Z

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


20\. 0과 1 사이 값을 가지는 크기 10의 실수 벡터 어레이 만들기, 0과 1은 포함되지 않는다.

In [20]:
Z = np.linspace(0, 1, 12, endpoint = True)[1: -1]
print Z

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


21\. 크기 10인 랜덤 벡터 어레이를 생성 후 정렬하기

In [21]:
Z = np.random.random(10)
Z.sort()
print Z

[ 0.11281264  0.16505544  0.19813187  0.32567049  0.3786303   0.45136616
  0.49380291  0.52166897  0.55808051  0.67484059]


22\. 두 벡터 어레이 A와 B가 같은지 체크하기

In [22]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print equal

False


23\. 벡터 어레이를 immutable(read-only)하게 바꾸기

In [23]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

24\. 직교좌표계를 나타내는 10 x 2 행렬 어레이를 극좌표계를 나타내도록 변환하기

In [24]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
P = np.dstack([R, T]).reshape(10, 2)
print P

[[ 0.39233909  0.37018462]
 [ 0.14083273  1.10066535]
 [ 1.00319066  0.77287387]
 [ 0.4623533   0.69094211]
 [ 0.89220552  0.57275476]
 [ 1.24209     0.64525674]
 [ 0.7670016   0.28559637]
 [ 1.27478791  0.88074726]
 [ 1.06640188  0.93402703]
 [ 1.19939874  0.59696966]]


25\. 크기 10인 랜덤 백터 어레이를 만들고, 최댓값을 0으로 바꾸기

In [25]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print Z

[ 0.03318188  0.3336954   0.22677746  0.66608007  0.05967092  0.65656545
  0.          0.62747823  0.57988218  0.37257097]


26\. `x`, `y` 좌표가 [0, 1] x [0, 1] 영역을 덮는 structured 어레이 생성하기

In [26]:
Z = np.zeros((10, 10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
print Z

[[(0.0, 0.0) (0.1111111111111111, 0.0) (0.2222222222222222, 0.0)
  (0.3333333333333333, 0.0) (0.4444444444444444, 0.0)
  (0.5555555555555556, 0.0) (0.6666666666666666, 0.0)
  (0.7777777777777777, 0.0) (0.8888888888888888, 0.0) (1.0, 0.0)]
 [(0.0, 0.1111111111111111) (0.1111111111111111, 0.1111111111111111)
  (0.2222222222222222, 0.1111111111111111)
  (0.3333333333333333, 0.1111111111111111)
  (0.4444444444444444, 0.1111111111111111)
  (0.5555555555555556, 0.1111111111111111)
  (0.6666666666666666, 0.1111111111111111)
  (0.7777777777777777, 0.1111111111111111)
  (0.8888888888888888, 0.1111111111111111) (1.0, 0.1111111111111111)]
 [(0.0, 0.2222222222222222) (0.1111111111111111, 0.2222222222222222)
  (0.2222222222222222, 0.2222222222222222)
  (0.3333333333333333, 0.2222222222222222)
  (0.4444444444444444, 0.2222222222222222)
  (0.5555555555555556, 0.2222222222222222)
  (0.6666666666666666, 0.2222222222222222)
  (0.7777777777777777, 0.2222222222222222)
  (0.8888888888888888, 0.222222222222

27\. 각 numpy 스칼라 타입들에 대해서 표현 가능한 최솟값과 최댓값 출력

In [27]:
for dtype in [np.int8, np.int32, np.int64]:
    print np.iinfo(dtype).min, np.iinfo(dtype).max
for dtype in [np.float32, np.float64]:
    print np.finfo(dtype).min, np.finfo(dtype).max, np.finfo(dtype).eps

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.40282e+38 3.40282e+38 1.19209e-07
-1.79769313486e+308 1.79769313486e+308 2.22044604925e-16


28\. 좌표 (x, y)와 색 (r, g, b)를 표현하는 structured 어레이 생성하기

In [28]:
Z = np.zeros(10, [('position', [('x', float, 1),
                               ('y', float, 1)]),
                  ('color', [('r', float, 1),
                            ('g', float, 1),
                            ('b', float, 1)])])
print Z

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))]


29\. (10, 2)의 shape를 가지는 랜덤 벡터 어레이가 있다고 할때, 모든 점과 점 사이의 거리를 구하기

In [29]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0]), np.atleast_2d(Z[:, 1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print D

import scipy
import scipy.spatial

Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z, Z)
print D

[[ 0.          0.5814241   0.68122477  0.19519383  0.74851313  0.24206392
   0.36205069  0.46823238  0.33595207  1.04269642]
 [ 0.5814241   0.          0.26973681  0.56127201  0.84431289  0.51253393
   0.24133533  0.17167928  0.25272484  0.71903429]
 [ 0.68122477  0.26973681  0.          0.57990133  0.65989934  0.51475131
   0.44026813  0.22978704  0.42852319  0.45193376]
 [ 0.19519383  0.56127201  0.57990133  0.          0.55376246  0.06740339
   0.40211221  0.40792808  0.36484191  0.8851534 ]
 [ 0.74851313  0.84431289  0.65989934  0.55376246  0.          0.5203176
   0.83309099  0.68308346  0.79601695  0.62289743]
 [ 0.24206392  0.51253393  0.51475131  0.06740339  0.5203176   0.
   0.37664159  0.35258475  0.33790976  0.81959511]
 [ 0.36205069  0.24133533  0.44026813  0.40211221  0.83309099  0.37664159
   0.          0.21837176  0.03911555  0.88052108]
 [ 0.46823238  0.17167928  0.22978704  0.40792808  0.68308346  0.35258475
   0.21837176  0.          0.20106228  0.66226884]
 [ 0.3359

30\. 아래와 같은 파일이 있다고 치자  
>1,2,3,4,5  
6,,,7,8  
,,9,10,11

어떻게 읽을 것인가?

In [30]:
text = """1,2,3,4,5
6,,,7,8
,,9,10,11"""
with open('missing.dat', 'w') as fp:
    fp.write(text)
Z = np.genfromtxt('missing.dat', delimiter=',')
print Z

[[  1.   2.   3.   4.   5.]
 [  6.  nan  nan   7.   8.]
 [ nan  nan   9.  10.  11.]]


31\. 가우시안 분포를 따르는 2차원 행렬 어레이 만들기

In [31]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma**2)))
print G

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

32\. n x n 영행렬 어레이의 랜덤한 곳에 m개의 p를 놓기

In [32]:
# Author: Divakar

n = 10
m = 3
p = 4
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), m, replace=False), p)
print Z

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  0.  0.  4.  0.]]


33\. 행렬의 각 행에서 평균 빼기

In [33]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent Ver. of numpy
Y1 = X - X.mean(axis=1, keepdims=True)

# Older Ver. of numpy
Y2 = X - X.mean(axis=1).reshape(-1, 1)

print Y1

[[ 0.2343738  -0.20183431 -0.22406926  0.12697114 -0.08531349 -0.30918044
  -0.24538385 -0.2283962   0.33106305  0.60176957]
 [ 0.26335561 -0.22660595 -0.55752491 -0.44381631  0.31608387  0.09498524
  -0.08093865  0.41121446  0.13582997  0.08741665]
 [-0.4334477  -0.16545007  0.13476815  0.20973772 -0.09725823 -0.28334453
   0.43908345 -0.34506745  0.10593795  0.43504071]
 [-0.00763055  0.27056309  0.1537525   0.11976854  0.07415388 -0.35096624
  -0.06093435 -0.33510672  0.41250971 -0.27610986]
 [ 0.09512403 -0.08226299 -0.34214868  0.19776968 -0.21827657  0.39458223
  -0.32391968 -0.08865888  0.37876388 -0.01097302]]


34\. 2차원 행렬 어레이에서 n번째 열 기준으로 정렬하기

In [37]:
# Author: Steve Tjoa

Z = np.random.randint(0, 10, (3, 3))
print Z
print Z[Z[:, 1].argsort()]

[[2 6 0]
 [6 5 8]
 [6 4 4]]
[[6 4 4]
 [6 5 8]
 [2 6 0]]


35\. 2차원 행렬 어레이가 영벡터 열을 가지고 있는지 판단하기

In [41]:
# Author: Warren Weckesser

Z = np.random.randint(0, 3, (3, 10))
print Z, (~Z.any(axis=0)).any()

[[0 0 1 1 0 2 0 1 2 0]
 [0 2 0 0 0 1 0 1 2 0]
 [0 1 2 1 2 0 0 2 1 0]] True


36\. 주어진 값과 가장 가까운 값을 어레이에서 찾아내기

In [42]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print m

0.509888436405


37\. 정수 10개를 generate하는 generator로부터 어레이 만들기

In [43]:
def generate():
    for x in xrange(10):
        yield x
Z = np.fromiter(generate(), dtype = float, count = -1)
print Z

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


38\. 주어진 벡터에 대해서, 두번째로 주어진 벡터에 쓰여있는 인덱스에 해당하는 원소만 1을 더하기 (인덱스는 중복 가능)

In [44]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength = len(Z))
print Z

[ 2.  4.  1.  3.  3.  3.  4.  1.  3.  6.]


39\. 인덱스 리스트 (I)에 기반하여 벡터 리스트 (X)를 어레이 (F)에 accumulate하기

In [45]:
# Author: Alan G Isaac

X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print F

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


40\. (w, h, 3, dtype = ubyte) 이미지가 주어졌을때, 색들의 종류의 개수를 구하기

In [54]:
# Author: Nadav Horesh

w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
F = I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))
print n

4


41\. 사차원 어레이가 주어졌을때, 마지막 두 차원의 합을 한번에 구하기

In [56]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
s = A.reshape(A.shape[:-2] + (-1, )).sum(axis = -1)
print s

[[61 62 68 47]
 [65 78 66 50]
 [47 45 71 52]]


42\. 일차원 벡터 어레이 D와 D의 각 원소가 속한 그룹을 적은 어레이 S가 주어졌을 때, 각 그룹별로 평균 구하기

In [58]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights = D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print D, S, D_sums

[ 0.48382992  0.90163571  0.54716449  0.09760475  0.81336974  0.31569926
  0.06925325  0.1088752   0.05644463  0.36409249  0.61086745  0.99354844
  0.79099137  0.19085004  0.37591572  0.36363514  0.36002937  0.03276379
  0.82852912  0.72398069  0.29040903  0.9239412   0.18390104  0.04147982
  0.2582508   0.07084409  0.36050842  0.90976074  0.9707976   0.92706072
  0.29364913  0.12871104  0.04625282  0.14430105  0.67503529  0.04297835
  0.19919423  0.42772349  0.06416773  0.51651087  0.24866954  0.95657255
  0.41636186  0.1595344   0.30314971  0.58484857  0.56706807  0.37222296
  0.15940645  0.8879628   0.33420632  0.71924269  0.95663494  0.69470347
  0.0845525   0.83658585  0.17898707  0.2128273   0.65112787  0.84272005
  0.10845893  0.56601011  0.21470339  0.56388527  0.54951486  0.77580283
  0.6254823   0.57450002  0.4935419   0.10908025  0.76210341  0.40628984
  0.10377035  0.38436459  0.45699098  0.85246212  0.07010238  0.06801495
  0.80195364  0.33760965  0.50432301  0.71808764  0